### ISSUE TITLE
Workflows are failing upload

### ISSUE THREAD

**Issue by ljmf00** [web3-storage/add-to-web3#21]
I just added a change to my blog posts and got a failed job due to add-to-web3 action failure. See https://github.com/ljmf00/lsferreira.net/actions/runs/1482056059 for context.

**Comment by alanshaw** [comment]
If you re-run does it still fail?

**Comment by ljmf00** [comment]
> If you re-run does it still fail?

Yes, I have done it three times to make sure.

**Comment by ljmf00** [comment]
The files get pinned anyway 
![image](https://user-images.githubusercontent.com/5050669/142676679-48669bc0-cd4e-401f-a649-6a1ebc93f2ee.png)

But because the job fails, the Cloudflare job doesn't update the DNS entry.

**Comment by ljmf00** [comment]
This is also happening on my automated task list, see here too: https://github.com/ljmf00/tasks/actions/runs/1482049459 . So I assume it is not my fault, but if it is, let me know. Anyway, I can provide more information if needed.

**Comment by rossneilson** [comment]
We are seeing similar issues

**Comment by ljmf00** [comment]
I can confirm this issue was fixed. @rossneilson, rerun the workflow pipeline and it will be fine. For context, this was the `web3.storage` rate limiter limiting GitHub actions hosts for too many requests, according to one member of the matrix channel. I'm closing this, but feel free to ask for a reopen if the problem presists.
