### ISSUE TITLE
Upgrade to work with w3up

### ISSUE THREAD

**Issue by gobengo** [web3-storage/add-to-web3#87]
This issue is to document how to use add-to-web3 with a w3up space. https://blog.web3.storage/posts/the-data-layer-is-here-with-the-new-web3-storage

I imagine I might need to pass a UCAN delegation to it and maybe also pass key material from a github secret that the ucan delegates to and that add-to-web3 can use to sign invocations of upload/add
```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/add-to-web3/pull/89
```

**Comment by olizilla** [comment]
My proposal for this is to upgrade w3cli to allow users to provide all the state explicitly per https://github.com/web3-storage/w3cli/issues/154

and then make the next version of `add-to-web3` be a yaml only "composite task" just like add-to-estuary was: https://github.com/olizilla/add-to-estuary
