### ISSUE TITLE
Need to support new Web3.stoarge API

### ISSUE THREAD

**Issue by Lu-Derik** [web3-storage/add-to-web3#88]
I have following error with web3-storage/add-to-web3@v2. When will V3 available? Thanks a lot !

Run web3-storage/add-to-web3@v2
  with:
    web_token: ***
    path_to_add: build
    include_hidden: false
    web3_api: https://api.web3.storage/
    wrap_with_directory: false
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Adding build to https://api.web3.storage/
Error: This API feature has been sunset, and is no longer available. To continue uploading, use the new web3.storage API: https://web3.storage/docs.
![image](https://github.com/web3-storage/add-to-web3/assets/117131602/30f3aab3-0ed2-43f8-8515-d668b5e6da25)

**Comment by olizilla** [comment]
Working on it! New version should land this week.

**Comment by olizilla** [comment]
The same issue is raised in #87 so I'm closing this issue out in favour of the earlier one.

The work on the v3 release that will fix this is happening in https://github.com/web3-storage/add-to-web3/pull/89/

**Comment by olizilla** [comment]
@Lu-Derik the new version of the add-to-web3 action that works with the new api is now published https://github.com/web3-storage/add-to-web3

**Comment by Lu-Derik** [comment]
You are great!
